//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KATEGORIEPJAZDY> KATEGORIEPJAZDY { get; set; }
        public virtual DbSet<KLIENCI> KLIENCI { get; set; }
        public virtual DbSet<OPINIA> OPINIA { get; set; }
        public virtual DbSet<POJAZDY> POJAZDY { get; set; }
        public virtual DbSet<PRACOWNICY> PRACOWNICY { get; set; }
        public virtual DbSet<PRZEGLADY> PRZEGLADY { get; set; }
        public virtual DbSet<REZERWACJE> REZERWACJE { get; set; }
        public virtual DbSet<ZDJECIA> ZDJECIA { get; set; }
        public virtual DbSet<LoginData> LoginData { get; set; }
        public virtual DbSet<MARKI> MARKI { get; set; }
    }
}
