//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPINIA
    {
        public int idOpinia { get; set; }
        public int REZERWACJE_idRezerw { get; set; }
        public System.DateTime DataWyst { get; set; }
        public short Ocena { get; set; }
        public string Opis { get; set; }
    
        public virtual REZERWACJE REZERWACJE { get; set; }
    }
}
