//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class POJAZDY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POJAZDY()
        {
            this.PRZEGLADY = new HashSet<PRZEGLADY>();
            this.REZERWACJE = new HashSet<REZERWACJE>();
            this.ZDJECIA = new HashSet<ZDJECIA>();
            this.KATEGORIEPJAZDY = new HashSet<KATEGORIEPJAZDY>();
        }
    
        public int idPojazd { get; set; }
        public short Rodzaj { get; set; }
        public string NrRejestr { get; set; }
        public int Przebieg { get; set; }
        public float ZaGodz { get; set; }
        public System.DateTime DataProd { get; set; }
        public sbyte Sprawny { get; set; }
        public string Opis { get; set; }
        public int MARKI_idMarki { get; set; }
        public string MARKA_Nazwa { get; set; }
        public string Kolor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRZEGLADY> PRZEGLADY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REZERWACJE> REZERWACJE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZDJECIA> ZDJECIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KATEGORIEPJAZDY> KATEGORIEPJAZDY { get; set; }
        public virtual MARKI MARKI { get; set; }
    }
}
