//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class REZERWACJE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REZERWACJE()
        {
            this.OPINIA = new HashSet<OPINIA>();
        }
    
        public int idRezerw { get; set; }
        public System.DateTime DataRez { get; set; }
        public System.DateTime DataWypoz { get; set; }
        public sbyte Wypozycz { get; set; }
        public System.DateTime DataZwrotu { get; set; }
        public Nullable<System.DateTime> DataZdania { get; set; }
        public int KLIENCI_idKlient { get; set; }
        public int POJAZDY_idPojazd { get; set; }
        public Nullable<int> PRACOWNICY_idPracWydaj { get; set; }
        public Nullable<int> PRACOWNICY_idPracOdbier { get; set; }
    
        public virtual KLIENCI KLIENCI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPINIA> OPINIA { get; set; }
        public virtual POJAZDY POJAZDY { get; set; }
        public virtual PRACOWNICY PRACOWNICY { get; set; }
        public virtual PRACOWNICY PRACOWNICY1 { get; set; }
    }
}
