//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZDJECIA
    {
        public int idZdjecia { get; set; }
        public int POJAZDY_idPojazd { get; set; }
        public byte[] Zdjecie { get; set; }
    
        public virtual POJAZDY POJAZDY { get; set; }
    }
}
